# This is a basic workflow to help you get started with Actions

name: PR Workflow for API Linting

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
jobs:
  send-pull-events:
    name: PR Workflow for API Linting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Vacuum Lint
        run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Analyze the Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
            vacuum lint -d $file
          done
